on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  build:
    needs: [ avoid_redundancy ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@2.4.2
      - name: Build app
        run: ./gradlew compileDebugSources

  testData:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@2.4.2

      - name: Unit Tests
        run: ./gradlew :data:testDebugUnitTest

      - name: Unit Tests Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  testDomain:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@2.4.2

      - name: Unit Tests
        run: ./gradlew :domain:testDebugUnitTest

      - name: Unit Tests Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  testApp:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@2.4.2

      - name: Unit Tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Unit Tests Report
        uses: asadmansr/android-test-report-action@v1.2.0
